CREATE DATABASE InLock_Games_Manha;
​
USE InLock_Games_Manha;
​
CREATE TABLE Estudio(
IdEstudio INT PRIMARY KEY IDENTITY,
NomeEstudio VARCHAR(255) NOT NULL
);
​
CREATE TABLE Jogos(
IdJogo INT PRIMARY KEY IDENTITY,
NomeJogo VARCHAR(255) NOT NULL,
Descricao VARCHAR(255) NOT NULL,
DataLancamento VARCHAR(255) NOT NULL,
Valor REAL NOT NULL,
IdEstudio INT FOREIGN KEY REFERENCES Estudio (IdEstudio)
);
​
CREATE TABLE TipoUsuarios(
IdTipoUsuario INT PRIMARY KEY IDENTITY,
Titulo VARCHAR(255) NOT NULL
);
​
CREATE TABLE Usuarios(
IdUsuario INT PRIMARY KEY IDENTITY,
Email VARCHAR(255) NOT NULL,
Senha VARCHAR(255) NOT NULL,
IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuarios (IdTipoUsuario)
);

DROP TABLE Usuarios;
DROP TABLE TipoUsuarios;
DROP TABLE Jogos;
DROP TABLE Estudio;

SELECT * FROM Usuarios;
SELECT * FROM TipoUsuarios;
SELECT * FROM Jogos;
SELECT * FROM Estudio;